@extends('layouts.admin')

@section('title', 'Fee Receipt')

@section('content')

<div class="max-w-4xl mx-auto">

    <!-- Top Buttons -->
    <div class="flex flex-col sm:flex-row justify-end gap-3 mb-6 print:hidden">

        <button onclick="window.print()"
            class="bg-blue-600 hover:bg-blue-700 text-white px-5 py-3 rounded-xl shadow font-medium">
            🖨 Print Receipt
        </button>

        <a href="{{ route('fee.receipt.pdf', $payment->id) }}"
           class="bg-green-600 hover:bg-green-700 text-white px-5 py-3 rounded-xl shadow font-medium text-center">
            Download PDF
        </a>

    </div>

    <!-- Receipt Card -->
    <div class="bg-white rounded-2xl shadow-2xl overflow-hidden border border-gray-200">

        <!-- Header -->
        <div class="bg-gradient-to-r from-indigo-700 to-blue-700 text-white px-8 py-6 text-center">

            <h1 class="text-3xl font-bold tracking-wide">
                School ERP
            </h1>

            <p class="text-blue-100 mt-2 text-lg">
                Fee Payment Receipt
            </p>

        </div>

        <!-- Body -->
        <div class="p-8">

            <!-- Student Details -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">

                <div class="bg-gray-50 rounded-xl p-4">
                    <p class="text-sm text-gray-500">Student Name</p>
                    <h3 class="text-lg font-semibold text-gray-800">
                        {{ $payment->student->name }}
                    </h3>
                </div>

                <div class="bg-gray-50 rounded-xl p-4">
                    <p class="text-sm text-gray-500">Class</p>
                    <h3 class="text-lg font-semibold text-gray-800">
                        {{ $payment->student->class }}
                    </h3>
                </div>

            </div>

            <!-- Table -->
            <div class="overflow-x-auto mb-8">

                <table class="w-full text-sm text-left border border-gray-200 rounded-xl overflow-hidden">

                    <thead class="bg-gray-100 text-gray-700 uppercase text-xs">
                        <tr>
                            <th class="px-6 py-4">Month</th>
                            <th class="px-6 py-4">Amount</th>
                        </tr>
                    </thead>

                    <tbody class="divide-y divide-gray-100">

                        @foreach($payment->allocations as $alloc)

                        <tr class="hover:bg-gray-50">

                            <td class="px-6 py-4 font-medium text-gray-800">
                                {{ $alloc->monthlyFee->month ?? '' }}
                            </td>

                            <td class="px-6 py-4 font-semibold text-green-600">
                                ₹{{ number_format($alloc->amount) }}
                            </td>

                        </tr>

                        @endforeach

                    </tbody>

                </table>

            </div>

            <!-- Summary -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">

                <div class="bg-green-50 border border-green-100 rounded-xl p-4">
                    <p class="text-sm text-gray-500">Total Paid</p>
                    <h3 class="text-xl font-bold text-green-700">
                        ₹{{ number_format($payment->amount) }}
                    </h3>
                </div>

                <div class="bg-blue-50 border border-blue-100 rounded-xl p-4">
                    <p class="text-sm text-gray-500">Date</p>
                    <h3 class="text-lg font-semibold text-blue-700">
                        {{ $payment->payment_date }}
                    </h3>
                </div>

                <div class="bg-purple-50 border border-purple-100 rounded-xl p-4">
                    <p class="text-sm text-gray-500">Payment Mode</p>
                    <h3 class="text-lg font-semibold text-purple-700 capitalize">
                        {{ $payment->payment_mode }}
                    </h3>
                </div>

            </div>

            <!-- Footer -->
            <div class="flex justify-between items-end pt-8">

                <div>
                    <p class="text-sm text-gray-500">
                        Generated by School ERP
                    </p>
                </div>

                <div class="text-center">
                    <div class="w-40 border-t border-gray-500 mb-2"></div>
                    <p class="font-medium text-gray-700">
                        Authorized Signature
                    </p>
                </div>

            </div>

        </div>

    </div>

</div>

@endsection